---
title: "Simulation Project"
author: "Ren Bettendorf, renb2"
date: "6/12/2019"
output: html_document
---

## Simulation Study 1: Significance of Regression


- **Introduction**
- **Methods**
```{r setup_model_1, message=FALSE, warning=FALSE}
birthday = 19890927
set.seed(birthday)
library(readr)
study_1_data = read_csv("study_1.csv")
n = 25
p = 3 + 1
x0 = rep(1, n)
x1 = study_1_data$x1
x2 = study_1_data$x2
x3 = study_1_data$x3

# Significant Model beta values
sig_beta_0 = 3
sig_beta_1 = 1
sig_beta_2 = 1
sig_beta_3 = 1
# Non-Significant Model beta values
non_beta_0 = 3
non_beta_1 = 0
non_beta_2 = 0
non_beta_3 = 0

sigma = c(1, 5, 10)
simulations = 2500
```

```{r simulate_model_1}
sim1_data = data.frame(sig_f = rep(0, simulations), sig_p = rep(0, simulations), sig_r = rep(0, simulations),
                       non_f = rep(0, simulations), non_p = rep(0, simulations), non_r = rep(0, simulations))
for (iter in 1:simulations) {
  eps = rnorm(n, mean = 0, sd = sigma[1])
  study_1_data$y = sig_beta_0 + sig_beta_1 * x1 + sig_beta_2 * x2 + sig_beta_3 * x3 + eps
  sig_model = lm(y ~ ., data = study_1_data)
  sim1_data$sig_f[iter] = summary(sig_model)$fstatistic[[1]]
  sim1_data$sig_p[iter] = pf(summary(sig_model)$fstatistic[[1]], df1 = p - 1, df2 = n - p, lower.tail = FALSE)
  sim1_data$sig_r[iter] = summary(sig_model)$r.squared
  
  study_1_data$y = non_beta_0 + non_beta_1 * x1 + non_beta_2 * x2 + non_beta_3 * x3 + eps
  non_model = lm(y ~ ., data = study_1_data)
  sim1_data$non_f[iter] = summary(non_model)$fstatistic[[1]]
  sim1_data$non_p[iter] = pf(summary(non_model)$fstatistic[[1]], df1 = p - 1, df2 = n - p, lower.tail = FALSE)
  sim1_data$non_r[iter] = summary(non_model)$r.squared
}

sim2_data = data.frame(sig_f = rep(0, simulations), sig_p = rep(0, simulations), sig_r = rep(0, simulations),
                       non_f = rep(0, simulations), non_p = rep(0, simulations), non_r = rep(0, simulations))
for (iter in 1:simulations) {
  eps = rnorm(n, mean = 0, sd = sigma[2])
  study_1_data$y = sig_beta_0 + sig_beta_1 * x1 + sig_beta_2 * x2 + sig_beta_3 * x3 + eps
  sig_model = lm(y ~ ., data = study_1_data)
  sim2_data$sig_f[iter] = summary(sig_model)$fstatistic[[1]]
  sim2_data$sig_p[iter] = pf(summary(sig_model)$fstatistic[[1]], df1 = p - 1, df2 = n - p, lower.tail = FALSE)
  sim2_data$sig_r[iter] = summary(sig_model)$r.squared
  
  study_1_data$y = non_beta_0 + non_beta_1 * x1 + non_beta_2 * x2 + non_beta_3 * x3 + eps
  non_model = lm(y ~ ., data = study_1_data)
  sim2_data$non_f[iter] = summary(non_model)$fstatistic[[1]]
  sim2_data$non_p[iter] = pf(summary(non_model)$fstatistic[[1]], df1 = p - 1, df2 = n - p, lower.tail = FALSE)
  sim2_data$non_r[iter] = summary(non_model)$r.squared
}

sim3_data = data.frame(sig_f = rep(0, simulations), sig_p = rep(0, simulations), sig_r = rep(0, simulations),
                       non_f = rep(0, simulations), non_p = rep(0, simulations), non_r = rep(0, simulations))
for (iter in 1:simulations) {
  eps = rnorm(n, mean = 0, sd = sigma[3])
  study_1_data$y = sig_beta_0 + sig_beta_1 * x1 + sig_beta_2 * x2 + sig_beta_3 * x3 + eps
  sig_model = lm(y ~ ., data = study_1_data)
  sim3_data$sig_f[iter] = summary(sig_model)$fstatistic[[1]]
  sim3_data$sig_p[iter] = pf(summary(sig_model)$fstatistic[[1]], df1 = p - 1, df2 = n - p, lower.tail = FALSE)
  sim3_data$sig_r[iter] = summary(sig_model)$r.squared
  
  study_1_data$y = non_beta_0 + non_beta_1 * x1 + non_beta_2 * x2 + non_beta_3 * x3 + eps
  non_model = lm(y ~ ., data = study_1_data)
  sim3_data$non_f[iter] = summary(non_model)$fstatistic[[1]]
  sim3_data$non_p[iter] = pf(summary(non_model)$fstatistic[[1]], df1 = p - 1, df2 = n - p, lower.tail = FALSE)
  sim3_data$non_r[iter] = summary(non_model)$r.squared
}
```

- **Results**
- **Discussion**

## Simulation Study 2: Using RMSE for Selection?

- **Introduction**
- **Methods**
```{r setup_simulate_2, message=FALSE, warning=FALSE}
birthday = 19890927
set.seed(birthday)
library(readr)
study_2_data = read_csv("study_2.csv")
n = nrow(study_2_data)
p = 3 + 1
x0 = rep(1, n)
x1 = study_2_data$x1
x2 = study_2_data$x2
x3 = study_2_data$x3
x4 = study_2_data$x4
x5 = study_2_data$x5
x6 = study_2_data$x6
sigma = c(1, 2, 4)

beta_0 = 0
beta_1 = 5
beta_2 = -4
beta_3 = 1.6
beta_4 = -1.1
beta_5 = 0.7
beta_6 = 0.3

simulations = 1000

calculate_rmse  = function(actual, predicted) {
  return(sqrt(mean((actual - predicted)^2)))
}
```
```{r simulate_models_2}
sim1_rmse_train = data.frame(model_1 = rep(0, simulations), model_2 = rep(0, simulations), model_3 = rep(0, simulations),
                             model_4 = rep(0, simulations), model_5 = rep(0, simulations), model_6 = rep(0, simulations),
                             model_7 = rep(0, simulations), model_8 = rep(0, simulations), model_9 = rep(0, simulations))
sim1_rmse_test = data.frame(model_1 = rep(0, simulations), model_2 = rep(0, simulations), model_3 = rep(0, simulations),
                            model_4 = rep(0, simulations), model_5 = rep(0, simulations), model_6 = rep(0, simulations),
                            model_7 = rep(0, simulations), model_8 = rep(0, simulations), model_9 = rep(0, simulations))
for (iter in 1:simulations) {
  eps = rnorm(n, mean = 0, sd = sigma[1])
  study_2_data$y = beta_0 + beta_1 * x1 +  beta_2 * x2 + beta_3 * x3 + beta_4 * x4 + beta_5 * x5 + beta_6 * x6 + eps
  
  train_index = sample(n / 2)
  train_data = study_2_data[train_index,]
  test_data = study_2_data[-train_index,]
  
  model_1 = lm(y ~ x1, data = train_data)
  model_2 = lm(y ~ x1 + x2, data = train_data)
  model_3 = lm(y ~ x1 + x2 + x3, data = train_data)
  model_4 = lm(y ~ x1 + x2 + x3 + x4, data = train_data)
  model_5 = lm(y ~ x1 + x2 + x3 + x4 + x5, data = train_data)
  model_6 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6, data = train_data)
  model_7 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7, data = train_data)
  model_8 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8, data = train_data)
  model_9 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9, data = train_data)
  
  sim1_rmse_train$model_1[iter] = calculate_rmse(train_data$y, predict(model_1, train_data))
  sim1_rmse_train$model_2[iter] = calculate_rmse(train_data$y, predict(model_2, train_data))
  sim1_rmse_train$model_3[iter] = calculate_rmse(train_data$y, predict(model_3, train_data))
  sim1_rmse_train$model_4[iter] = calculate_rmse(train_data$y, predict(model_4, train_data))
  sim1_rmse_train$model_5[iter] = calculate_rmse(train_data$y, predict(model_5, train_data))
  sim1_rmse_train$model_6[iter] = calculate_rmse(train_data$y, predict(model_6, train_data))
  sim1_rmse_train$model_7[iter] = calculate_rmse(train_data$y, predict(model_7, train_data))
  sim1_rmse_train$model_8[iter] = calculate_rmse(train_data$y, predict(model_8, train_data))
  sim1_rmse_train$model_9[iter] = calculate_rmse(train_data$y, predict(model_9, train_data))
  
  sim1_rmse_test$model_1[iter] = calculate_rmse(test_data$y, predict(model_1, test_data))
  sim1_rmse_test$model_2[iter] = calculate_rmse(test_data$y, predict(model_2, test_data))
  sim1_rmse_test$model_3[iter] = calculate_rmse(test_data$y, predict(model_3, test_data))
  sim1_rmse_test$model_4[iter] = calculate_rmse(test_data$y, predict(model_4, test_data))
  sim1_rmse_test$model_5[iter] = calculate_rmse(test_data$y, predict(model_5, test_data))
  sim1_rmse_test$model_6[iter] = calculate_rmse(test_data$y, predict(model_6, test_data))
  sim1_rmse_test$model_7[iter] = calculate_rmse(test_data$y, predict(model_7, test_data))
  sim1_rmse_test$model_8[iter] = calculate_rmse(test_data$y, predict(model_8, test_data))
  sim1_rmse_test$model_9[iter] = calculate_rmse(test_data$y, predict(model_9, test_data))
}

sim2_rmse_train = data.frame(model_1 = rep(0, simulations), model_2 = rep(0, simulations), model_3 = rep(0, simulations),
                             model_4 = rep(0, simulations), model_5 = rep(0, simulations), model_6 = rep(0, simulations),
                             model_7 = rep(0, simulations), model_8 = rep(0, simulations), model_9 = rep(0, simulations))

sim2_rmse_test = data.frame(model_1 = rep(0, simulations), model_2 = rep(0, simulations), model_3 = rep(0, simulations),
                            model_4 = rep(0, simulations), model_5 = rep(0, simulations), model_6 = rep(0, simulations),
                            model_7 = rep(0, simulations), model_8 = rep(0, simulations), model_9 = rep(0, simulations))

for (iter in 1:simulations) {
  eps = rnorm(n, mean = 0, sd = sigma[2])
  study_2_data$y = beta_0 + beta_1 * x1 +  beta_2 * x2 + beta_3 * x3 + beta_4 * x4 + beta_5 * x5 + beta_6 * x6 + eps
  
  train_index = sample(n / 2)
  train_data = study_2_data[train_index,]
  test_data = study_2_data[-train_index,]
  
  model_1 = lm(y ~ x1, data = train_data)
  model_2 = lm(y ~ x1 + x2, data = train_data)
  model_3 = lm(y ~ x1 + x2 + x3, data = train_data)
  model_4 = lm(y ~ x1 + x2 + x3 + x4, data = train_data)
  model_5 = lm(y ~ x1 + x2 + x3 + x4 + x5, data = train_data)
  model_6 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6, data = train_data)
  model_7 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7, data = train_data)
  model_8 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8, data = train_data)
  model_9 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9, data = train_data)
  
  
  sim2_rmse_train$model_1[iter] = calculate_rmse(train_data$y, predict(model_1, train_data))
  sim2_rmse_train$model_2[iter] = calculate_rmse(train_data$y, predict(model_2, train_data))
  sim2_rmse_train$model_3[iter] = calculate_rmse(train_data$y, predict(model_3, train_data))
  sim2_rmse_train$model_4[iter] = calculate_rmse(train_data$y, predict(model_4, train_data))
  sim2_rmse_train$model_5[iter] = calculate_rmse(train_data$y, predict(model_5, train_data))
  sim2_rmse_train$model_6[iter] = calculate_rmse(train_data$y, predict(model_6, train_data))
  sim2_rmse_train$model_7[iter] = calculate_rmse(train_data$y, predict(model_7, train_data))
  sim2_rmse_train$model_8[iter] = calculate_rmse(train_data$y, predict(model_8, train_data))
  sim2_rmse_train$model_9[iter] = calculate_rmse(train_data$y, predict(model_9, train_data))
  
  sim2_rmse_test$model_1[iter] = calculate_rmse(test_data$y, predict(model_1, test_data))
  sim2_rmse_test$model_2[iter] = calculate_rmse(test_data$y, predict(model_2, test_data))
  sim2_rmse_test$model_3[iter] = calculate_rmse(test_data$y, predict(model_3, test_data))
  sim2_rmse_test$model_4[iter] = calculate_rmse(test_data$y, predict(model_4, test_data))
  sim2_rmse_test$model_5[iter] = calculate_rmse(test_data$y, predict(model_5, test_data))
  sim2_rmse_test$model_6[iter] = calculate_rmse(test_data$y, predict(model_6, test_data))
  sim2_rmse_test$model_7[iter] = calculate_rmse(test_data$y, predict(model_7, test_data))
  sim2_rmse_test$model_8[iter] = calculate_rmse(test_data$y, predict(model_8, test_data))
  sim2_rmse_test$model_9[iter] = calculate_rmse(test_data$y, predict(model_9, test_data))
}

sim3_rmse_train = data.frame(model_1 = rep(0, simulations), model_2 = rep(0, simulations), model_3 = rep(0, simulations),
                             model_4 = rep(0, simulations), model_5 = rep(0, simulations), model_6 = rep(0, simulations),
                             model_7 = rep(0, simulations), model_8 = rep(0, simulations), model_9 = rep(0, simulations))

sim3_rmse_test = data.frame(model_1 = rep(0, simulations), model_2 = rep(0, simulations), model_3 = rep(0, simulations),
                            model_4 = rep(0, simulations), model_5 = rep(0, simulations), model_6 = rep(0, simulations),
                            model_7 = rep(0, simulations), model_8 = rep(0, simulations), model_9 = rep(0, simulations))

for (iter in 1:simulations) {
  eps = rnorm(n, mean = 0, sd = sigma[3])
  study_2_data$y = beta_0 + beta_1 * x1 +  beta_2 * x2 + beta_3 * x3 + beta_4 * x4 + beta_5 * x5 + beta_6 * x6 + eps
  
  train_index = sample(n / 2)
  train_data = study_2_data[train_index,]
  test_data = study_2_data[-train_index,]
  
  model_1 = lm(y ~ x1, data = train_data)
  model_2 = lm(y ~ x1 + x2, data = train_data)
  model_3 = lm(y ~ x1 + x2 + x3, data = train_data)
  model_4 = lm(y ~ x1 + x2 + x3 + x4, data = train_data)
  model_5 = lm(y ~ x1 + x2 + x3 + x4 + x5, data = train_data)
  model_6 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6, data = train_data)
  model_7 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7, data = train_data)
  model_8 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8, data = train_data)
  model_9 = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9, data = train_data)
  
  
  
  sim3_rmse_train$model_1[iter] = calculate_rmse(train_data$y, predict(model_1, train_data))
  sim3_rmse_train$model_2[iter] = calculate_rmse(train_data$y, predict(model_2, train_data))
  sim3_rmse_train$model_3[iter] = calculate_rmse(train_data$y, predict(model_3, train_data))
  sim3_rmse_train$model_4[iter] = calculate_rmse(train_data$y, predict(model_4, train_data))
  sim3_rmse_train$model_5[iter] = calculate_rmse(train_data$y, predict(model_5, train_data))
  sim3_rmse_train$model_6[iter] = calculate_rmse(train_data$y, predict(model_6, train_data))
  sim3_rmse_train$model_7[iter] = calculate_rmse(train_data$y, predict(model_7, train_data))
  sim3_rmse_train$model_8[iter] = calculate_rmse(train_data$y, predict(model_8, train_data))
  sim3_rmse_train$model_9[iter] = calculate_rmse(train_data$y, predict(model_9, train_data))
  
  sim3_rmse_test$model_1[iter] = calculate_rmse(test_data$y, predict(model_1, test_data))
  sim3_rmse_test$model_2[iter] = calculate_rmse(test_data$y, predict(model_2, test_data))
  sim3_rmse_test$model_3[iter] = calculate_rmse(test_data$y, predict(model_3, test_data))
  sim3_rmse_test$model_4[iter] = calculate_rmse(test_data$y, predict(model_4, test_data))
  sim3_rmse_test$model_5[iter] = calculate_rmse(test_data$y, predict(model_5, test_data))
  sim3_rmse_test$model_6[iter] = calculate_rmse(test_data$y, predict(model_6, test_data))
  sim3_rmse_test$model_7[iter] = calculate_rmse(test_data$y, predict(model_7, test_data))
  sim3_rmse_test$model_8[iter] = calculate_rmse(test_data$y, predict(model_8, test_data))
  sim3_rmse_test$model_9[iter] = calculate_rmse(test_data$y, predict(model_9, test_data))
}
```

- **Results**
- **Discussion**

## Simulation Study 3: Power

- **Introduction**
- **Methods**
```{r setup_power_values}
birthday = 19890927
set.seed(birthday)
beta_0 = 0
beta_1_list = seq(-2, 2, .1)
sigmas = c(1, 2, 4)
samples = c(10, 20, 30)
alpha = 0.05
simulations = 1000
number_iterations = length(sigmas) * length(samples) * length(beta_1_list)
power_data = data.frame(sigma = rep(0, number_iterations), n = rep(0, number_iterations),
                        beta_1 = rep(0, number_iterations), power = rep(0, number_iterations))
```
```{r simulate_power}
i = 1
for (sigma in sigmas) {
  for (n in samples) {
    x_values = seq(0, 5, length = n)
    for (beta_1 in beta_1_list) {
      rejected = 0
      for (iter in 1:simulations) {
        eps = rnorm(n, 0, sigma)
        y = beta_0 + beta_1 * x_values + eps
        model = lm(y ~ x_values)
        beta_1_p = summary(model)$coefficients[2, 4]
        if (beta_1_p < alpha) {
          rejected = rejected + 1
        }
      }
      power = rejected / simulations
      power_data$sigma[i] = sigma
      power_data$n[i] = n
      power_data$beta_1[i] = beta_1
      power_data$power[i] = power
      i = i + 1
    }
  }
}
```
```{r calculate_mean_sigma}
mean_sigmas = rep(0, length(sigmas))
i = 1
for (sigma in sigmas) {
  mean_sigmas[i] = mean(power_data$power[power_data$sigma == sigma])
  i = i + 1
}
```
```{r calculate_mean_beta_1}
mean_beta_1s = rep(0, length(beta_1_list))
i = 1
for (beta_1 in beta_1_list) {
  mean_beta_1s[i] = mean(power_data$power[power_data$beta_1 == beta_1])
  i = i + 1
}
```
```{r calculate_mean_sample_size}
mean_n = rep(0, length(samples))
i = 1
for (sample in samples) {
  mean_n[i] = mean(power_data$power[power_data$n == sample])
  i = i + 1
}
```


- **Results**
- **Discussion**